### PR TITLE
Replace ModelSchema with SQLAlchemyAutoSchema

### PR DESCRIPTION
**Pull request by JDeeth**
Fixes 8

### CODE REVIEW

**Comment by JDeeth** [comment]
I've only done this for the final step - would it be beneficial if I changed it for all steps and included inline comments explaining the discrepancies?

Incidentally, my own API project, heavily inspired by this one, is working now, so thanks again for the ongoing inspiration!

**Comment by singingwolfboy** [comment]
@JDeeth yes, that would be very helpful! Keep in mind that most people looking at this repo are interested in learning step-by-step -- it's confusing if something suddenly changes from one step to another, without an explanation in the associated `README.rst` file.

As much as I like the idea of merging your change, I'm afraid that right now it would cause _more_ confusion rather than less!

**Comment by JDeeth** [comment]
Righto, I've updated the previous steps also, and added a note to the Step09 readme.

**Comment by singingwolfboy** [comment]
Looks great! Thank you 🙏

**Comment by JDeeth** [comment]
Brilliant! Cheers :)

**Pull request merged**
